services:
  backend:
    build: ./backend
    ports:
      - 3010:3010
    depends_on:
      - database
    volumes:
      - ./backend:/app

  database:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ro0tPass
      POSTGRES_DB: hubcook
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
